default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development_2

test:
  <<: *default
  database: rails-watch-list_test_2
